export const EFeedbackAction = {
  POST_FEEDBACK: 'POST_FEEDBACK',
  POST_FEEDBACK_REQUEST: 'POST_FEEDBACK_REQUEST',
  POST_FEEDBACK_SUCCESS: 'POST_FEEDBACK_SUCCESS',
  POST_FEEDBACK_FAILED: 'POST_FEEDBACK_FAILED',
};
