export const ERateProductAction = {
  //  POST-RATE-PRODUCT
  POST_RATE_PRODUCT: 'POST_RATE_PRODUCT',
  POST_RATE_PRODUCT_REQUEST: 'POST_RATE_PRODUCT_REQUEST',
  POST_RATE_PRODUCT_SUCCESS: 'POST_RATE_PRODUCT_SUCCESS',
  POST_RATE_PRODUCT_FAILED: 'POST_RATE_PRODUCT_FAILED',

  // GET-RATE-PRODUCT
  GET_RATE_PRODUCT: 'GET_RATE_PRODUCT',
  GET_RATE_PRODUCT_REQUEST: 'GET_RATE_PRODUCT_REQUEST',
  GET_RATE_PRODUCT_SUCCESS: 'GET_RATE_PRODUCT_SUCCESS',
  GET_RATE_PRODUCT_FAILED: 'GET_RATE_PRODUCT_FAILED',

  // GET-RATE-PRODUCT
  GET_RATE_STATISTIC_PRODUCT: 'GET_RATE_STATISTIC_PRODUCT',
  GET_RATE_STATISTIC_PRODUCT_REQUEST: 'GET_RATE_STATISTIC_PRODUCT_REQUEST',
  GET_RATE_STATISTIC_PRODUCT_SUCCESS: 'GET_RATE_STATISTIC_PRODUCT_SUCCESS',
  GET_RATE_STATISTIC_PRODUCT_FAILED: 'GET_RATE_STATISTIC_PRODUCT_FAILED',
};
