export const EBannerAction = {
  GET_BANNERS: 'GET_BANNERS',
  GET_BANNERS_REQUEST: 'GET_BANNERS_REQUEST',
  GET_BANNERS_SUCCESS: 'GET_BANNERS_SUCCESS',
  GET_BANNERS_FAILED: 'GET_BANNERS_FAILED',
};
