export const EIconName = {
  ArrowCircleLeft: 'ArrowCircleLeft',
  ArrowCircleRight: 'ArrowCircleRight',
  Facebook: 'Facebook',
  GooglePlus: 'GooglePlus',
  Notification: 'Notification',
  Phone: 'Phone',
  Search: 'Search',
  ShoppingBag: 'ShoppingBag',
  Twitter: 'Twitter',
  Youtube: 'Youtube',
  MapMarker: 'MapMarker',
  Mail: 'Mail',
  ArrowLeft: 'ArrowLeft',
  Plus: 'Plus',
  Minus: 'Minus',
  Close: 'Close',
  Trash: 'Trash',
  Filter: 'Filter',
  CaretDown: 'CaretDown',
  Star: 'Star',
  AngleRight: 'AngleRight',
  MapMarkerFill: 'MapMarkerFill',
  PlusCircle: 'PlusCircle',
  BookArrow: 'BookArrow',
  Book: 'Book',
  BookMark: 'BookMark',
  Chat: 'Chat',
  GridPlus: 'GridPlus',
  L: 'L',
  Locked: 'Locked',
  Logout: 'Logout',
  Question: 'Question',
  UserSquare: 'UserSquare',
  MailFill: 'MailFill',
  Camera: 'Camera',
  Website: 'Website',
  PhoneFill: 'PhoneFill',
  Check: 'Check',
  Play: 'Play',
  Pdf: 'Pdf',
  Menu: 'Menu',
};

export const EIconColor = {
  BLACK: '#000',
  WHITE: '#fff',
  MAKO: '#3B4045',
  FUN_GREEN: '#016938',
  OLIVE_DRAB: '#55AB29',
  BLUE_ZODIAC: '#0F2E53',
  GRAY: '#808080',
  SUNGLOW: '#FBBA32',
  GRENADIER: '#CF3605',
  ALTO: '#e0e0e0',
};
