export const EAuthorAction = {
  GET_AUTHORS: 'GET_AUTHORS',
  GET_AUTHORS_REQUEST: 'GET_AUTHORS_REQUEST',
  GET_AUTHORS_SUCCESS: 'GET_AUTHORS_SUCCESS',
  GET_AUTHORS_FAILED: 'GET_AUTHORS_FAILED',
};
