export const ENewAction = {
  GET_LIST_NEW: 'GET_LIST_NEW_',
  GET_LIST_NEW_REQUEST: 'GET_LIST_NEW_REQUEST',
  GET_LIST_NEW_SUCCESS: 'GET_LIST_NEW_SUCCESS',
  GET_LIST_NEW_FAILED: 'GET_LIST_NEW_FAILED',

  // AUDIO
  GET_LIST_NEW_LATEST: 'GET_LIST_NEW_LATEST',
  GET_LIST_NEW_LATEST_REQUEST: 'GET_LIST_NEW_LATEST_REQUEST',
  GET_LIST_NEW_LATEST_SUCCESS: 'GET_LIST_NEW_LATEST_SUCCESS',
  GET_LIST_NEW_LATEST_FAILED: 'GET_LIST_NEW_LATEST_FAILED',
  //Detail
  GET_DETAIL_NEW: 'GET_DETAIL_NEW',
  GET_DETAIL_NEW_REQUEST: 'GET_DETAIL_NEW_REQUEST',
  GET_DETAIL_NEW_SUCCESS: 'GET_DETAIL_NEW_SUCCESS',
  GET_DETAIL_NEW_FAILED: 'GET_DETAIL_NEW_FAILED',
};
