export const EProductAction = {
  GET_LIST_PRODUCT_PAPER: 'GET_LIST_PRODUCT_PAPER',
  GET_LIST_PRODUCT_PAPER_REQUEST: 'GET_LIST_PRODUCT_PAPER_REQUEST',
  GET_LIST_PRODUCT_PAPER_SUCCESS: 'GET_LIST_PRODUCT_PAPER_SUCCESS',
  GET_LIST_PRODUCT_PAPER_FAILED: 'GET_LIST_PRODUCT_PAPER_FAILED',

  // AUDIO
  GET_LIST_PRODUCT_AUDIO: 'GET_LIST_PRODUCT_AUDIO',
  GET_LIST_PRODUCT_AUDIO_REQUEST: 'GET_LIST_PRODUCT_AUDIO_REQUEST',
  GET_LIST_PRODUCT_AUDIO_SUCCESS: 'GET_LIST_PRODUCT_AUDIO_SUCCESS',
  GET_LIST_PRODUCT_AUDIO_FAILED: 'GET_LIST_PRODUCT_AUDIO_FAILED',
};
