export const EProductAction = {
  GET_LIST_PRODUCT_PAPER: 'GET_LIST_PRODUCT_PAPER',
  GET_LIST_PRODUCT_PAPER_REQUEST: 'GET_LIST_PRODUCT_PAPER_REQUEST',
  GET_LIST_PRODUCT_PAPER_SUCCESS: 'GET_LIST_PRODUCT_PAPER_SUCCESS',
  GET_LIST_PRODUCT_PAPER_FAILED: 'GET_LIST_PRODUCT_PAPER_FAILED',

  // AUDIO
  GET_LIST_PRODUCT_AUDIO: 'GET_LIST_PRODUCT_AUDIO',
  GET_LIST_PRODUCT_AUDIO_REQUEST: 'GET_LIST_PRODUCT_AUDIO_REQUEST',
  GET_LIST_PRODUCT_AUDIO_SUCCESS: 'GET_LIST_PRODUCT_AUDIO_SUCCESS',
  GET_LIST_PRODUCT_AUDIO_FAILED: 'GET_LIST_PRODUCT_AUDIO_FAILED',
  // Searchh
  GET_LIST_PRODUCT_SEARCH: 'GET_LIST_PRODUCT_SEARCH',
  GET_LIST_PRODUCT_SEARCH_REQUEST: 'GET_LIST_PRODUCT_SEARCH_REQUEST',
  GET_LIST_PRODUCT_SEARCH_SUCCESS: 'GET_LIST_PRODUCT_SEARCH_SUCCESS',
  GET_LIST_PRODUCT_SEARCH_FAILED: 'GET_LIST_PRODUCT_SEARCH_FAILED',
  //Detail
  GET_DETAIL_PRODUCT: 'GET_DETAIL_PRODUCT',
  GET_DETAIL_PRODUCT_REQUEST: 'GET_DETAIL_PRODUCT_REQUEST',
  GET_DETAIL_PRODUCT_SUCCESS: 'GET_DETAIL_PRODUCT_SUCCESS',
  GET_DETAIL_PRODUCT_FAILED: 'GET_DETAIL_PRODUCT_FAILED',
  //add to cart
  ADD_TO_CART_PRODUCT: 'ADD_TO_CART_PRODUCT',
  ADD_TO_CART_PRODUCT_REQUEST: 'ADD_TO_CART_PRODUCT_REQUEST',
  ADD_TO_CART_PRODUCT_SUCCESS: 'ADD_TO_CART_PRODUCT_SUCCESS',
  ADD_TO_CART_PRODUCT_FAILED: 'ADD_TO_CART_PRODUCT_FAILED',
  //List Cart
  LIST_CART_PRODUCT: 'LIST_CART_PRODUCT',
  LIST_CART_PRODUCT_REQUEST: 'LIST_CART_PRODUCT_REQUEST',
  LIST_CART_PRODUCT_SUCCESS: 'LIST_CART_PRODUCT_SUCCESS',
  LIST_CART_PRODUCT_FAILED: 'LIST_CART_PRODUCT_FAILED',
  //Update Cart
  UPDATE_CART_PRODUCT: 'UPDATE_CART_PRODUCT',
  UPDATE_CART_PRODUCT_REQUEST: 'UPDATE_CART_PRODUCT_REQUEST',
  UPDATE_CART_PRODUCT_SUCCESS: 'UPDATE_CART_PRODUCT_SUCCESS',
  UPDATE_CART_PRODUCT_FAILED: 'UPDATE_CART_PRODUCT_FAILED',
  //Delete Cart
  DELETE_CART_PRODUCT: 'DELETE_CART_PRODUCT',
  DELETE_CART_PRODUCT_REQUEST: 'DELETE_CART_PRODUCT_REQUEST',
  DELETE_CART_PRODUCT_SUCCESS: 'DELETE_CART_PRODUCT_SUCCESS',
  DELETE_CART_PRODUCT_FAILED: 'DELETE_CART_PRODUCT_FAILED',
};
