export const EAddressAction = {
  ADDRESS_LIST: 'ADDRESS_LIST',
  ADDRESS_LIST_REQUEST: 'ADDRESS_LIST_REQUEST',
  ADDRESS_LIST_SUCCESS: 'ADDRESS_LIST_SUCCESS',
  ADDRESS_LIST_FAILED: 'ADDRESS_LIST_FAILED',

  GET_ADDRESS_DEFAULT: 'GET_ADDRESS_DEFAULT',
  GET_ADDRESS_DEFAULT_REQUEST: 'GET_ADDRESS_DEFAULT_REQUEST',
  GET_ADDRESS_DEFAULT_SUCCESS: 'GET_ADDRESS_DEFAULT_SUCCESS',
  GET_ADDRESS_DEFAULT_FAILED: 'GET_ADDRESS_DEFAULT_FAILED',
  //add address
  ADDRESS_ADD: 'ADDRESS_ADD',
  ADDRESS_ADD_REQUEST: 'ADDRESS_ADD_REQUEST',
  ADDRESS_ADD_SUCCESS: 'ADDRESS_ADD_SUCCESS',
  ADDRESS_ADD_FAILED: 'ADDRESS_ADD_FAILED',

  ADDRESS_UPDATE: 'ADDRESS_UPDATE',
  ADDRESS_UPDATE_REQUEST: 'ADDRESS_UPDATE_REQUEST',
  ADDRESS_UPDATE_SUCCESS: 'ADDRESS_UPDATE_SUCCESS',
  ADDRESS_UPDATE_FAILED: 'ADDRESS_UPDATE_FAILED',

  //add address
  GET_PROVINCE: 'GET_PROVINCE',
  GET_PROVINCE_REQUEST: 'GET_PROVINCE_REQUEST',
  GET_PROVINCE_SUCCESS: 'GET_PROVINCE_SUCCESS',
  GET_PROVINCE_FAILED: 'GET_PROVINCE_FAILED',
  //add address
  GET_DISTRICT: 'GET_DISTRICT',
  GET_DISTRICT_REQUEST: 'GET_DISTRICT_REQUEST',
  GET_DISTRICT_SUCCESS: 'GET_DISTRICT_SUCCESS',
  GET_DISTRICT_FAILED: 'GET_DISTRICT_FAILED',
  //add address
  GET_WARD: 'GET_WARD',
  GET_WARD_REQUEST: 'GET_WARD_REQUEST',
  GET_WARD_SUCCESS: 'GET_WARD_SUCCESS',
  GET_WARD_FAILED: 'GET_WARD_FAILED',
  //Fee ship
  CACULATE_FEE_SHIP: 'CACULATE_FEE_SHIP',
  CACULATE_FEE_SHIP_REQUEST: 'CACULATE_FEE_SHIP_REQUEST',
  CACULATE_FEE_SHIP_SUCCESS: 'CACULATE_FEE_SHIP_SUCCESS',
  CACULATE_FEE_SHIP_FAILED: 'CACULATE_FEE_SHIP_FAILED',
};
