export const ENotiAction = {
  GET_NOTICE: 'GET_NOTICE',
  GET_NOTICE_REQUEST: 'GET_NOTICE_REQUEST',
  GET_NOTICE_SUCCESS: 'GET_NOTICE_SUCCESS',
  GET_NOTICE_FAILED: 'GET_NOTICE_FAILED',
  // Update profile
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',
};
