export const EUploadFileAction = {
  UPLOAD_FILE: 'UPLOAD_FILE',
  UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_FAILED: 'UPLOAD_FILE_FAILED',
};
