export const EProfileAction = {
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILED: 'GET_PROFILE_FAILED',
  // Update profile
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',
  // My Book
  MY_BOOK: 'MY_BOOK',
  MY_BOOK_REQUEST: 'MY_BOOK_REQUEST',
  MY_BOOK_SUCCESS: 'MY_BOOK_SUCCESS',
  MY_BOOK_FAILED: 'MY_BOOK_FAILED',

  GET_FILE_MY_BOOK: 'GET_FILE_MY_BOOK',
  GET_FILE_MY_BOOK_REQUEST: 'GET_FILE_MY_BOOK_REQUEST',
  GET_FILE_MY_BOOK_SUCCESS: 'GET_FILE_MY_BOOK_SUCCESS',
  GET_FILE_MY_BOOK_FAILED: 'MY_BOOK_FAILED',

  GET_VOICE_MY_BOOK: 'GET_VOICE_MY_BOOK',
  GET_VOICE_MY_BOOK_REQUEST: 'GET_VOICE_MY_BOOK_REQUEST',
  GET_VOICE_MY_BOOK_SUCCESS: 'GET_VOICE_MY_BOOK_SUCCESS',
  GET_VOICE_MY_BOOK_FAILED: 'GET_VOICE_MY_BOOK_FAILED',
};
